# Generated by Django 4.0.4 on 2022-05-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('pkilometrico', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mercave.linea')),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercave.puntored')),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercave.puntored')),
            ],
        ),
        migrations.AlterField(
            model_name='circulacion',
            name='loc_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mercave.final'),
        ),
        migrations.AlterField(
            model_name='circulacion',
            name='loc_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mercave.inicio'),
        ),
    ]
