# Generated by Django 4.0.4 on 2022-05-05 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0002_linea_puntored_inicio_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulacion',
            name='pfinal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.final'),
        ),
        migrations.AddField(
            model_name='circulacion',
            name='pinicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.inicio'),
        ),
        migrations.AlterField(
            model_name='circulacion',
            name='loc_final',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='circulacion',
            name='loc_inicio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
