# Generated by Django 4.0.4 on 2022-05-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0004_remove_circulacion_loc_final_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='final',
            old_name='codigo',
            new_name='puntored',
        ),
        migrations.RenameField(
            model_name='inicio',
            old_name='codigo',
            new_name='puntored',
        ),
    ]
