# Generated by Django 4.0.4 on 2022-05-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0005_rename_codigo_final_puntored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmacirculacion',
            name='lat',
            field=models.FloatField(blank=True, default=40.2951, null=True),
        ),
        migrations.AddField(
            model_name='alarmacirculacion',
            name='lng',
            field=models.FloatField(blank=True, default=-3.982, null=True),
        ),
    ]
