# Generated by Django 4.0.4 on 2022-05-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0006_alarmacirculacion_lat_alarmacirculacion_lng'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circulacion',
            new_name='CirculacionEje',
        ),
        migrations.RemoveField(
            model_name='eje',
            name='alarmas_cambio',
        ),
        migrations.RemoveField(
            model_name='eje',
            name='alarmas_circulacion',
        ),
        migrations.AddField(
            model_name='eje',
            name='alarmas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vagon',
            name='num_bogies',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='vagon',
            name='num_ejes',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='eje',
            name='vagon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.vagon'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='composicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.composicion'),
        ),
        migrations.CreateModel(
            name='CirculacionVagon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('Vmed', models.FloatField(default=2.77)),
                ('km', models.FloatField(default=340)),
                ('alarmas', models.BooleanField(default=False)),
                ('pfinal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.final')),
                ('pinicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.inicio')),
                ('vagon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercave.vagon')),
            ],
        ),
        migrations.CreateModel(
            name='Bogie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('tipo', models.CharField(default=' ', max_length=20)),
                ('foto', models.ImageField(blank=True, upload_to='bogies/')),
                ('lng', models.FloatField(default=-3.982)),
                ('lat', models.FloatField(default=40.2951)),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mercave.keeper')),
                ('mantenedor', models.ForeignKey(limit_choices_to={'de_vagones': True}, on_delete=django.db.models.deletion.RESTRICT, to='mercave.mantenedor')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mercave.operador')),
                ('vagon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.vagon')),
            ],
        ),
        migrations.AddField(
            model_name='eje',
            name='bogie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.bogie'),
        ),
    ]
