# Generated by Django 4.0.4 on 2022-05-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0007_rename_circulacion_circulacioneje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmacirculacion',
            name='circulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercave.circulacioneje'),
        ),
        migrations.CreateModel(
            name='PuntoTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('circulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercave.circulacioneje')),
                ('punto_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercave.puntored')),
            ],
        ),
        migrations.CreateModel(
            name='CirculacionComposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('Vmed', models.FloatField(default=2.77)),
                ('km', models.FloatField(default=340)),
                ('alarmas', models.BooleanField(default=False)),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercave.composicion')),
                ('pfinal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.final')),
                ('pinicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.inicio')),
            ],
        ),
        migrations.AddField(
            model_name='alarmacirculacion',
            name='punto_transito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercave.puntotransito'),
        ),
    ]
