# Generated by Django 4.0.4 on 2022-05-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0008_alter_alarmacirculacion_circulacion_puntotransito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogie',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.keeper'),
        ),
        migrations.AlterField(
            model_name='bogie',
            name='mantenedor',
            field=models.ForeignKey(limit_choices_to={'de_bogies': True}, on_delete=django.db.models.deletion.RESTRICT, to='mercave.mantenedor'),
        ),
        migrations.AlterField(
            model_name='bogie',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.operador'),
        ),
        migrations.AlterField(
            model_name='composicion',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mercave.operador'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.keeper'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='mantenedor',
            field=models.ForeignKey(blank=True, limit_choices_to={'de_vagones': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.mantenedor'),
        ),
        migrations.AlterField(
            model_name='vagon',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.operador'),
        ),
        migrations.AlterField(
            model_name='versioncambiador',
            name='fabricante',
            field=models.ForeignKey(blank=True, limit_choices_to={'de_cambiadores': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.fabricante'),
        ),
    ]
