# Generated by Django 4.0.4 on 2022-05-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0009_alter_bogie_keeper_alter_bogie_mantenedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eje',
            name='mantenimiento',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
