# Generated by Django 4.0.4 on 2022-05-12 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0010_alter_eje_mantenimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntored',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='puntored',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mercave.linea'),
        ),
    ]
