# Generated by Django 4.0.4 on 2022-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0011_remove_puntored_codigo_alter_puntored_linea'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntored',
            name='codigo',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
