# Generated by Django 4.0.4 on 2022-05-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercave', '0012_puntored_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntored',
            name='codigo',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
